### ISSUE TITLE
Create release v0.7.1

### ISSUE THREAD

**Issue by danielhjacobs** [Ethiraric/yaml-rust2#16]
Mainly just to fix #8. Since that includes breaking changes, it would be better to do this before the general Rust ecosystem updates to this fork, so that the crates doing the updates can address the breaking changes immediately.

**Comment by torokati44** [comment]
+1 ^^

**Comment by davvid** [comment]
Heads-up @Ethiraric  I'll update the changelog and release this as v0.8.0 shortly. I'll push a signed tag as well.

**Comment by davvid** [comment]
https://crates.io/crates/yaml-rust2/0.8.0
