### ISSUE TITLE
Serde support?

### ISSUE THREAD

**Issue by luben** [Ethiraric/yaml-rust2#18]
Are there plans to add `serde` support? Possibly enabled through cargo feature.

I think this is opportunity as `serde_yaml` just got unmaintained.

**Comment by Ethiraric** [comment]
This is a possibility that is currently being discussed in #17.

I had not anticipated `serde_yaml` to get unmaintained. The best we can do is try to rebuild a better YAML ecosystem from the ground up (in terms of repositories, organization, ...)

**Comment by Ethiraric** [comment]
So, serde support will not come with `yaml-rust2` but with `saphyr`. I'm closing this issue here as Github won't let me transfer it and someone already opened one on `saphyr`.
