### ISSUE TITLE
Question: Multi-Document Examples

### ISSUE THREAD

**Issue by Narwhalrus** [Ethiraric/yaml-rust2#22]
The quick start example mentions that `YamlLoader` supports loading multiple documents, but I didn't find any examples or tests that load multiple documents. My expectation was that a "document" in this context would be a single file, but there must be some distinction in the spec I'm not aware of.

Could you please provide a simple example of how to use yaml-rust2 to load multiple documents?

**Comment by Narwhalrus** [comment]
Nevermind. Upon more reading of the YAML spec it's clear what a document refers to. For anyone else who happens across this: https://yaml.org/spec/1.2.2/#91-documents

**Comment by Ethiraric** [comment]
Indeed, this would be a YAML with multiple documents:
```yaml
---
First: document
---
Second: document
...
---
Third document
```

`---` starts documents while `...` ends them. `---` is optional for the first document and `...` is always optioonal iirc.
