### ISSUE TITLE
No error on duplicated keys

### ISSUE THREAD

**Issue by joergdw** [Ethiraric/yaml-rust2#23]
Dear maintainers!

I have here an issue regarding non-matching the YAML-specification. What is your view? Can we users get that fixed?

Here the description:

In the YAML-specification it is [stated](<https://yaml.org/spec/1.2.2/#nodes>) that each key in a map is _unique_. However it seems that yaml-rust2 does not throw an error when parsing a map with a duplicate-key, as e.g. [serde_yaml](<https://docs.rs/serde_yaml/0.9.34+deprecated/src/serde_yaml/mapping.rs.html#817>). This has two downsides:
- The implementation does not match the specification of YAML.
- Duplicated keys are an issue on their own as it is unclear, which value one gets out of a map. This leads to problems in software … The yaml should be rejected instead.

Example:
```rust
use yaml_rust2::YamlLoader;

fn main() {
    let raw_yaml = r#"
a: "hello"
a: "world"
"#;
    let docs = YamlLoader::load_from_str(raw_yaml).unwrap();
    println!("{:?}", docs);
}
```
It prints out `[Hash({String("a"): String("world")})]` instead of failing.

**Comment by Ethiraric** [comment]
Heya,

That is indeed not caught by the yaml-test-suite, which requires parsers emit the events without complaining.
I get why that is an issue, and I definitely thought that either `yaml-rust` would have implemented that already or that the yaml-test-suite would have caught it.

I'll get to it. Thanks for reporting!

**Comment by joergdw** [comment]
Thank you @Ethiraric. And thank you in general for your work on this library!

**Comment by Ethiraric** [comment]
You're welcome! Glad this can be of use! :)
