### ISSUE TITLE
Extra new line when parsing literal style multiline string

### ISSUE THREAD

**Issue by zim32** [Ethiraric/yaml-rust2#25]
I was testing this lib and got strange behaviour.
Example code:

```rust
let mut parser = Parser::new_from_str(r#"
>
This is
multiline
string"#);

loop {
    match parser.next_token() {
        Ok((event, _marker)) => {
            println!("{:?}", event);

            if let Event::StreamEnd = event {
                exit(0);
            }
        }
        Err(e) => { panic!("{}", e); }
    };
}
```

This code emits this events:

```
StreamStart
DocumentStart
Scalar("This is multiline string\n", Folded, 0, None)
DocumentEnd
StreamEnd
```

Expected: no new line character in the end of the string

**Comment by davvid** [comment]
Multiline block strings intentionally end with a newline. I'm relying on that behavior, at least.

The "chomping" modifier https://yaml-multiline.info/ can be used with block scalars to strip the trailing newline.

I'm not sure if this is related to this issue, though. I'm just pointing out that:

```yaml
block-scalar: |
   example
   text
```
does currently behave correctly and the resulting string is `example\ntest\n` with a trailing newline.

```yaml
chomped-block-scalar: |-
  example
  text
```

is the chomping modifier (note the `|-`) that strips the trailing newline and results in `example\ntest`.

This might be unrelated to the topic in this issue, though.

**Comment by zim32** [comment]
Hm. I guess this phrase 

The [chomping indicator](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator) controls what should happen with newlines at the end of the string.

is talking about new lines which EXISTS in the source string. If there is no new lines in the source string, they should not be added. At least when I test here https://yaml-online-parser.appspot.com/ no new line is added if source data has no new line

**Comment by zim32** [comment]
Here is example what I am talking about

![image](https://github.com/Ethiraric/yaml-rust2/assets/538976/5b3e2433-75c7-4ecb-8bea-afce58bb7023)

**Comment by davvid** [comment]
The page I linked says:

> The default, clip, puts a single newline at the end of the string.

which makes me believe this is the correct behavior. Remember, newlines are line terminators, not line separators, and the block is implied to end with a newline (even if the file doesn't terminate with one) unless you use the chomp indicator.

**Comment by Ethiraric** [comment]
https://play.yaml.io/main/parser?input=PgpUaGlzIGlzCm11bHRpbGluZQpzdHJpbmc=

This would be the reference parser, which has a trailing newline.

**Comment by zim32** [comment]
I think yaml specification is missing something because I can see different implementations give different result in this example https://play.yaml.io/main/parser?input=aGVsbG86IHwKICBmaXJzdAogIHNlY29uZAogIHRoaXJk

**Comment by Ethiraric** [comment]
Unfortunately, the YAML ecosystem is highly fragmented. Not all parsers are 100% compliant, and some purposefully diverged from the specification. There are gaps between the current practice and YAML compliance. For instance, an issue was posted here (#11) which takes Unity's parser as an example, which parses correctly a non YAML-compliant document.

You can see [here](https://matrix.yaml.info/) how compliant each parser is with the specification. If using the YAML playground, the reference parser is to be trusted. `libfyaml` is a nice source as well. The error messages are much clearer than the reference parser and it passes the whole yaml test suite.

**Comment by zim32** [comment]
> The page I linked says:
> 
> > The default, clip, puts a single newline at the end of the string.
> 
> which makes me believe this is the correct behavior. Remember, newlines are line terminators, not line separators, and the block is implied to end with a newline (even if the file doesn't terminate with one) unless you use the chomp indicator.

Yeah I understand. I am writing serde integration for this lib and in current situation if I am trying to deserialize just multiline string literal which does not have a new line in the end, I got string with new line as a result. Wich seems a little bit odd. I will mention in documentation about that behaviour

**Comment by zim32** [comment]
Also this is offtopic questiona but why you return owned String in events? This makes imposible to deserialize into &str

**Comment by Ethiraric** [comment]
This crate is meant to be a "maintained" fork of `yaml-rust` more than an evolving library. I'm currently working on improving the API and performance more, but this would require bumping the major version frequently and having users update their code each time. The original `yaml-rust` crate did return a `String` and I left that part of the code this way.

The major design decision preventing me from returning a `Cow<'a, str>` is the way characters are input into the parser. Currently, the parser takes its input from an `Iterator<Item = char>`. I'll need to change that since the type is too opaque I cannot extract substrings out of that.

If you're writing a serde wrapper, you might consider using [saphyr-parser](https://github.com/saphyr-rs/saphyr-parser/) instead. As of now, that and `yaml-rust2` are very similar, but I do plan on having `saphyr-parser` evolve. I was also planning on releasing a serde crate there but haven't had time yet to start working on it.

**Comment by zim32** [comment]
I am a little bit confused. saphyr and this lib looks similar in terms of API. What is the difference?

**Comment by Ethiraric** [comment]
This library won't see any API change. It is intended for people who are just looking for a `yaml-rust` replacement. Only bug fixes will end up here.

`saphyr` will have bugfixes + new features and evolve while `yaml-rust2` will remain "feature-frozen">

**Comment by zim32** [comment]
Ok got it. I think I can create a serde integration crate for this "frozen" lib. Because it is already implemented.
Also I can try to create same crate for saphyr too, but if you are saying it will evolve much, then it will be hard to keep them in sync

**Comment by Ethiraric** [comment]
You may target a specific release of `saphyr` for an initial serde release and then slowly update it.

You mentioned that you wanted to deserialize into `&str`. That's something that unfortunately won't come in `yaml-rust2`.

Though in the end, it all depends on your usecase.
