### ISSUE TITLE
How to access Tags

### ISSUE THREAD

**Issue by rob-p** [Ethiraric/yaml-rust2#31]
Hi,

  Thanks for the library!  I'm looking to do YAML parsing in rust and will be dealing with documents that make extensive use of tags (i.e. `!Foo`).  Looking through the documentation, it wasn't immediately clear to me how I can access tags in parsed YAML documents using the `yaml-rust2` library, and they didn't seem to have an associated variant in the [Yaml enum](https://docs.rs/yaml-rust2/latest/yaml_rust2/yaml/enum.Yaml.html).  Could you suggest how I can best parse and access the tag information?

Thanks!

**Comment by Ethiraric** [comment]
Hello,

There is no easy way in `yaml-rust2` to access tags. This crate focuses only on being a maintained replacement for `yaml_rust`, which did not support tags either.
[`saphyr`](https://github.com/saphyr-rs/saphyr), which intends to become a fully-fledged YAML library, will have support for that. There's already an issue opened for that, with a suggested API for that.

If you need to access tags, you should be able to retrieve them using the low-level parsing API and building objects manually from the events.
You can find the parser [here](https://docs.rs/yaml-rust2/latest/yaml_rust2/parser/struct.Parser.html) and look at the [loader](https://docs.rs/yaml-rust2/latest/src/yaml_rust2/yaml.rs.html#120)'s implementation for reference.

I am closing this issue, but do feel free to keep using it; I will monitor and reply.
