### ISSUE TITLE
Tag handle support

### ISSUE THREAD

**Issue by mrgrain** [Ethiraric/yaml-rust2#34]
Hi everyone,

I ended up here following a long chain of links. Basically I am after support for Tag handles.
The approach propsed in https://github.com/chyh1990/yaml-rust/pull/135 would suit me.

This [comment](https://github.com/chyh1990/yaml-rust/issues/35#issuecomment-1913876546) and [this one](https://github.com/chyh1990/yaml-rust/pull/135#issuecomment-1913875449) by @davvid indicated that the respective PR made it into the `davvid/yaml-rust2` fork. Subsequently it looks like this fork was abandoned in favor of this of this one (`Ethiraric/yaml-rust2`) - yay for consolidating! 

However it appears that the specific feature didn't actually end up in here. I was wondering if there was a particular reason for it and if you would be open to a PR.

Another option could be to make the loader more composable. Right now I basically need a carbon copy of `YamlLoader` which my changes. But if `insert_new_node` were public, and every event would call a public function - then I could create a much simpler wrapper struct.

Thoughts?

**Comment by Ethiraric** [comment]
Davvid and I merged our work together. It was helped by the fact they mostly work on the api and yaml object manipulation and I on the parsing. I wasn't aware of a feature that was lost in the process. 

Tags should be exposed via the low level parsing api. 

I'll look this (EU) evening into more details. Especially if it changes the api. 

Saphyr has an issue with a design I like for tags. This may be an option for the future.

**Comment by mrgrain** [comment]
Thanks for your response. I've started investigating as well and turns out the linked PR isn't really enough either. That only covers scalars, but tags can be used for anything! 

Happy to move this discussion to saphyr. I understand now that the API here should stay the same.

**Comment by Ethiraric** [comment]
Saphyr is under development and the api may often break. You need to keep this in mind while making your choice. 

Although the tags are not part of the high level api, maybe see if it's possible for you to implement an `EventReceiver`, which should give you access to tags.

**Comment by Ethiraric** [comment]
I'm unable to focus at the moment. I'll have to postpone my looking into this matter to tomorrow, sorry.

**Comment by Ethiraric** [comment]
> Another option could be to make the loader more composable

Without inducing huge API changes, I don't think we can do that. Aside from copy-pasting the loader and making the changes you need, I see no option. Very little has changed in `YamlLoader`. Even though duplicating code is never a good option, it should be _fine_.

Saphyr will have proper tag handling. [This](https://github.com/saphyr-rs/saphyr/issues/4) is the issue I was referencing and I'll probably go for something close to what is suggested here :)

**Comment by mrgrain** [comment]
Excellent. I'll have a look at the issue in saphyr and will make sure to share my requirements. In the meantime, I'm going with the copy and modify approach of the loader.

**Comment by Ethiraric** [comment]
Heya! I'm cleaning up my notifications so I'll be closing this issue as it seems there's nothing to act upon in this repository.

Do feel free to re-open should you feel the need to! :)
