### ISSUE TITLE
Info: How to maintain insert order for Yaml::Hash

### ISSUE THREAD

**Issue by qtfkwk** [Ethiraric/yaml-rust2#35]
Just sharing a recent experience from a `yaml-rust2` user perspective... and hopefully help anyone else who runs into this, **since hashlink's documentation doesn't directly advise this**.

Background: I made [`merge-yaml-hash`](https://github.com/qtfkwk/merge-yaml-hash) as a way to easily merge YAML hashes, which depends on `yaml-rust`.
Then I made [`yaml-hash`](https://github.com/qtfkwk/yaml-hash) as a fork to depend instead on `yaml-rust2` 0.5.0.

When I recently updated to use `yaml-rust2` 0.8.1, I noticed the swap from `linked-hash-map` to `hashlink`, and while it was mostly seamless, it caused a couple tests to fail because insertion order was not being maintained.

To restore that functionality, it was necessary to [replace the entry / and_modify / or_insert_with pattern with the contains_key / replace / insert pattern](https://github.com/qtfkwk/yaml-hash/commit/1f7f036b3b8e942c59bd6eac6d693e0f8e8dbfaa#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759), since hashlink's insert methods explicitly move entries to the end:

> "Methods that have the word `insert` will insert a new entry to the back of the list, and if that method might replace an entry, that method will *also move that existing entry to the back*."
>
> https://docs.rs/hashlink/0.8.4/hashlink/linked_hash_map/struct.LinkedHashMap.html

The former pattern also used `linked_hash_map::Entry::Occupied` enum variant directly and this change also enabled me to remove it as a direct dependency.

Hope it helps!

**Comment by Ethiraric** [comment]
Heya! I apologize for the delay.

I have to ask whether
> insertion order was not being maintained

refers to what you encountered while you _merged_ 2 YAML documents or if it is the order while `yaml-rust2` _parsed_ a YAML document.

The latter would be a bug in `yaml-rust2`, as we make the guarantee that the order of insertion in `Yaml::Hash` matches that in which we encounter the mappings in the source YAML document.

**Comment by qtfkwk** [comment]
@Ethiraric, it was the former case (merging 2 yaml documents), and the behavior matches the guarantees given by `hashlink::linked_hash_map::LinkedHashMap`
