### ISSUE TITLE
invalid indentation in quoted scalar

### ISSUE THREAD

**Issue by huguesb** [Ethiraric/yaml-rust2#40]
I am trying to parse a  bunch of yaml files, some of which contain PEM encoded certificates as quoted multiline strings, with the "----- BEGIN ..." line on the same line as the key, and subsequent lines having no indentation, e.g:

```
foo:
  certificate: "-----BEGIN CERTIFICATE-----
qwertyuio....
asdfghjk...
...
-----END CERTIFICATE-----"
  foo: bar
...
```

I understand that for this particular use case, a block scalar would have been more appropriate, but as far as I can tell, this is still legal YAML: libyaml accepts it, so does the pure Python yaml parser, and `yamllint` doesn't even issue a warning about it...

**Comment by Ethiraric** [comment]
On [the parser playground](https://play.yaml.io/main/parser?input=Zm9vOgogIGNlcnRpZmljYXRlOiAiLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCnF3ZXJ0eXVpby4uLi4KYXNkZmdoamsuLi4KLi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0iCiAgZm9vOiBiYXIKLi4u), the input is rejected by `libyaml`, `PyYAML` and `Ruamel` (Python). I know not which is the pure Python YAML parser you mention.

Unfortunately, your input is invalid due to indentation in the double quoted string. As per [7.3.1](https://yaml.org/spec/1.2.2/#731-double-quoted-style), double quoted strings are a flow scalar style and, as scalars, have to respect line prefixes described in [6.3](https://yaml.org/spec/1.2.2/#63-line-prefixes). This latter section namely states (emphasis mine):
> Inside scalar content, each line begins with a non-content line prefix. **This prefix always includes the indentation.**

The correct YAML here would be:
```yaml
foo:
  certificate: "-----BEGIN CERTIFICATE-----
    qwertyuio....
    asdfghjk...
    ...
    -----END CERTIFICATE-----"
  foo: bar
...
```
You need 2 leading spaces in your content for `certificate`'s indent, plus at least one other for the scalar's block.

**Comment by huguesb** [comment]
i'm not able to use the playground easily, however, my experience with libyaml and Python yaml is markedly different:

The files I have to deal with are accepted by Python's `yaml` module at least at version `5.1.1` with the plain python implementation, and at version `5.4.1` with the `libyaml` backend.

Additionally, my reading of the spec is that indentation only has structural relevant for *block* scalars, not for *flow* scalars:

Following the link to "indentation" from section 6.3 you linked, takes us to section 6.1 :

> 6.1. Indentation Spaces
> In YAML [block styles](https://yaml.org/spec/1.2.2/#block-style-productions), structure is determined by indentation.

Following to section 8.1 which describes block styles, we see an explicit callout to indentation. Contrast that with chapter 7 which describes flow productions and makes no mention of indentation...

Or consider from section 2.1
> YAML also has [flow styles](https://yaml.org/spec/1.2.2/#flow-style-productions), using explicit [indicators](https://yaml.org/spec/1.2.2/#indicator-characters) rather than [indentation](https://yaml.org/spec/1.2.2/#indentation-spaces) to denote scope.

Which suggests that quoted *flow* scalars, for which quotes is an *explicit indicator* should probably not be treated at block scalars...

**Comment by huguesb** [comment]
Also accepted by `ruamel.yaml` at version `0.16.2`

**Comment by huguesb** [comment]
Also accepted by golang: https://go.dev/play/p/fCi3b6B589G

**Comment by Ethiraric** [comment]
Even if you do not spawn the Docker container for the added parsers, you should see that the reference parser, which runs in your browser, rejects your input.

---

Your excerpt from section [2.1](https://yaml.org/spec/1.2.2/#21-collections) is about flow collections and not scalars, but there still are restrictions with those. For instance, the following is invalid if the leading space at lines 2 or 3 is removed:
```yaml
foo: [
 bar
 ]
```
---

Section [6.1](https://yaml.org/spec/1.2.2/#61-indentation-spaces) states that:
> A block style construct is terminated when encountering a line which is less indented than the construct.

And is confirmed further by:

> Each node must be indented further than its parent node.

In your example, the unindented lines would end the mapping node they are part of:
```yaml
foo: # Mapping #1, the "root" node
  # Here begins mapping #2, the value of the `foo` key in mapping #1
  certificate: "-----BEGIN CERTIFICATE-----
  # The line below ends mapping #2
qwertyuio....
asdfghjk...
...
-----END CERTIFICATE-----"
  foo: bar
...
```

Scalars are nodes and thus your whole scalar must be indented further.

---

The yaml-test-suite has [a test](https://github.com/yaml/yaml-test-suite/blob/main/src/JKF3.yaml) with this. Although the double quoted string is used there as a key, the example can be reduced and [shown to be rejected](https://play.yaml.io/main/parser?input=LSAtICJiYXIKYmFyIg==).

**Comment by hugues-aff** [comment]
<img width="1675" alt="Screenshot 2024-11-22 at 6 32 28 PM" src="https://github.com/user-attachments/assets/de0b68f2-812e-44b6-874c-ee1976abb5a4">

**Comment by Ethiraric** [comment]
I would also like to highlight that non-compliant YAML is all too common. You can see on the [yaml test matrix](https://matrix.yaml.info/) that a lot of parsers have at least edge cases where they do not conform to the specification. Even Unity [distributes invalid YAML](https://github.com/Ethiraric/yaml-rust2/issues/11#issuecomment-2016831747).

I do not consider "X and Y parsers do not reject that input" as valid arguments. I do mostly follow the reference parser and [libfyaml](https://github.com/pantoniou/libfyaml), which is the first parser to successfully pass the yaml test suite.

**Comment by huguesb** [comment]
> I would also like to highlight that non-compliant YAML is all too common. You can see on the [yaml test matrix](https://matrix.yaml.info/) that a lot of parsers have at least edge cases where they do not conform to the specification. Even Unity [distributes invalid YAML](https://github.com/Ethiraric/yaml-rust2/issues/11#issuecomment-2016831747).

Wow! I knew YAML was overly complex and confusing but I had no idea just how bad the situation was until I read through the spec and looked at this test matrix...

> I do not consider "X and Y parsers do not reject that input" as valid arguments.

Fair. I would like to have a way to relax this particular constraint for the purpose of parsing inputs that I am not in a position to easily fix but I understand that it's not in your interest to accommodate this, so I'll just have to patch this on my own...

**Comment by Ethiraric** [comment]
I didn't think making `yaml-rust` compliant would be such a hassle either. I thought YAML was just a happy little language with spaces as indentation.

The function you'll need to modify, if you want to use this project as a base is [`scan_flow_scalar`](https://github.com/Ethiraric/yaml-rust2/blob/master/src/scanner.rs#L1916). You'll probably have to remove some tests as well if you want to use `cargo test`.

**Comment by huguesb** [comment]
> The function you'll need to modify, if you want to use this project as a base is [`scan_flow_scalar`](https://github.com/Ethiraric/yaml-rust2/blob/master/src/scanner.rs#L1916). You'll probably have to remove some tests as well if you want to use `cargo test`.

Yeah, I already made a fork and removed that indendation check. It works fine for my use case.
I also discovered in the process that multiple yaml files in the dump I have to work with have duplicate mapping keys that other parsers blissfully accept. I'm getting around this one by just processing the event stream from the parser...

Thanks for writing this library and educating me about YAML compliance!

**Comment by Ethiraric** [comment]
[This](https://github.com/Ethiraric/yaml-rust2/blob/master/src%2Fyaml.rs#L223) is the check that handles duplicates. You can change the behaviour there. There is no sensible default here so I left it as an error. 

You're welcome! Hope that was a nice introduction to the world of Yaml :p
