### ISSUE TITLE
switch the 'encoding' dependency to 'encoding_rs'?

### ISSUE THREAD

**Issue by zh-jq-b** [Ethiraric/yaml-rust2#8]
See https://github.com/rustsec/advisory-db/issues/1605

**Comment by Ethiraric** [comment]
@davvid This is an API-breaking change. Considering not many people yet depend on `yaml-rust2` yet, I think we can fix this quickly and release `0.7.1`.

I don't see any trap-like functionality in `encoding_rs` (I merely glanced at it). What feature of it were you depending on?

**Comment by davvid** [comment]
Yeah, ideally we could switch over but if there's no equivalent functionality then this might be something that we have to consider dropping in the short-term.

The `encoding` dependency was added to get code simlar to [this test](https://github.com/Ethiraric/yaml-rust2/blob/master/src/yaml.rs#L619) working with the YamlDecoder builder from 0ea4178f21a138044f74e57cb4b8d6bb9c998388.

That behavior allows yaml-rust to process files that contain invalid content by stripping out the invalid bytes. It's kind of questionable and I imagine that it might not be the best thing from a performance perspective but it'd be good to see if others are relying on this functionality.

@mkmik authored the original patch against yaml-rust. @mkmik is this a key feature that you're relying on?

A transitional option might be to disable this feature by default and hide it behind a cargo feature flag. That way if someone really needs this functionality they can opt-in to it in the short-term. That wouldn't drop the dependency outright but it would buy us time to see whether an alternative is available or materializes. If time passes and there's not a strong case for the feature then we can drop it.

**Comment by Ethiraric** [comment]
I think the `Ignore` trap should be something we can find in `encoding_rs`. I'm more sceptical about finding an equivalent of the "custom function call" trap.

There's [`encoding_rs::Encoding::for_bom`](https://docs.rs/encoding_rs/latest/encoding_rs/struct.Encoding.html#method.for_bom) we could use along with its [`new_decoder`](https://docs.rs/encoding_rs/latest/encoding_rs/struct.Encoding.html#method.new_decoder) method to get a decoder. We can then use [`encoding_rs::Decoder::decode_to_utf8`](https://docs.rs/encoding_rs/latest/encoding_rs/struct.Decoder.html#method.decode_to_utf8).

We should be able to do:
* `encoding::types::DecoderTrap::Replace`: By just returning the output
* `encoding::types::DecoderTrap::Strict`: By observing the return value from `decode_to_utf8` which returns somewhere in the tuple the number of replacement sequences that were emitted
* `encoding::types::DecoderTrap::Ignore`: By post-processing the output and removing the unicode replacement character

I don't see however how we could mimic `encoding::types::DecoderTrap::Call`. That's the only part of the API we'd need to drop support for.
